### 브랜드 등록
POST {{commerce-api}}/api-admin/v1/brands
X-Loopers-AdminLdap: admin
Content-Type: application/json

{
  "name": "나이키",
  "description": "스포츠 브랜드"
}

### 브랜드 목록 조회
GET {{commerce-api}}/api-admin/v1/brands?page=0&size=10
X-Loopers-AdminLdap: admin

### 브랜드 상세 조회
GET {{commerce-api}}/api-admin/v1/brands/1
X-Loopers-AdminLdap: admin

### 브랜드 수정
PUT {{commerce-api}}/api-admin/v1/brands/1
X-Loopers-AdminLdap: admin
Content-Type: application/json

{
  "name": "아디다스",
  "description": "독일 스포츠 브랜드"
}

### 브랜드 삭제
DELETE {{commerce-api}}/api-admin/v1/brands/1
X-Loopers-AdminLdap: admin
